### ISSUE TITLE
Error in conversion of timestamp_tz from resultset

### ISSUE THREAD

**Issue by satyashani** [StrideSpark/snowflake-sdk#2]
When timestamp_tz field in the resultset is converted to Javascript Date object, and the timezone of system is different from UTC, then value of field is changed.

Test steps : 
create table test ( timefield timestamptz); 
insert into test values( '2017-05-08T08:06:38.549Z' );
value of 'timefield' obtained from sf-sdk  : 2017-05-08T02:36:38.549Z

**Comment by scottbessler** [comment]
@satyashani sorry for just now getting back to you, but this is just an extracted version of the official node driver, so don't want to merge anything in. thanks tho!
